#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: scrartcl
#+LATEX_CLASS_OPTIONS: [a4paper,14pt,ngerman]
#+OPTIONS: ':t toc:nil title:nil

#+LANGUAGE: de

#+LATEX_HEADER: \usepackage{polyglossia}
#+LATEX_HEADER: \setdefaultlanguage{german}
#+LATEX_HEADER: \PolyglossiaSetup{german}{shorthands=on}
#+LATEX_HEADER: \AtBeginDocument{\let\babelprovide\relax}
#+LATEX_HEADER: \AtBeginDocument{\let\shorthandon\relax}
#+LATEX_HEADER: \AtBeginDocument{\let\shorthandoff\relax}
#+LATEX_HEADER: \setmainfont{Gentium Book Basic}
#+LATEX_HEADER: \setsansfont{Latin Modern Sans}
#+LATEX_HEADER: \setmonofont{Latin Modern Mono}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{amsmath,amssymb}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{xurl}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \setstretch{1.3}

#+title: Übungsblatt 4

* *Übung 4*
** *Eigenschaften regulärer bzw. kontextfreier Sprachen, Chomsky-Normalform und CYK-Algorithmus*

Hinweis: Zur Lösung der Aufgaben 1 bis 5 dieser Serie greifen Sie auf
das Pumping-Lemma bzw. die Abschlusseigenschaften der jeweiligen
Sprachklasse zurück.

*** *Aufgabe 1*

Zeigen Sie, dass die Sprache \(L= \{scs \mid s \in \{a, b\}^* \}\) nicht
regulär ist.

*** *Aufgabe 2*

Zeigen Sie, dass die Sprache \(L= \{scs \mid s \in \{a, b\}^* \}\) nicht
kontextfrei ist.

*** *Aufgabe 3*

\(L\) sei regulär und werde durch einen DFA mit 4 Zuständen akzeptiert.
\(L\) enthalte ein Wort der Länge 4. Ist \(L\) unendlich? Begründen Sie
die Antwort.

*** *Aufgabe 4*

Seien \(L_1, L_2 \subseteq \Sigma^*\) zwei Sprachen. \(L_1\) und
\(L=L_1 \cup L_2\) seien regulär.

Es gelte \(L_1 \cap L_2 = \varnothing\). Beweisen Sie: \(L_2\) ist
regulär.

*** *Aufgabe 5*

Zeigen Sie: die folgende Sprache ist nicht kontextfrei:
\[L=\{w \in \{a, b, c\}^* \mid |w|_a=|w|_b=|w|_c\}\] Dabei bezeichnet
\(|w|_a\) die Anzahl von \(a\)'s im Wort \(w\).

*** *Aufgabe 6*

Gegeben sei \[G=(\{S,A,B\},\{a,b,c\},P,S)\] mit der Produktionsmenge
\(P\): \\

\[\begin{aligned}
        S \rightarrow & aAb \mid aBb\\
        A \rightarrow & S \mid aaSc \mid B \mid \varepsilon\\
\end{aligned}\]

Überführen Sie diese Grammatik in Chomsky-Normalform.

*** *Aufgabe 7*

Gegeben sei folgende Grammatik \(G\) in Chomsky-Normalform: \\

\[\begin{aligned}
        S \rightarrow & AB\\
        A \rightarrow & X_aX_b \mid X_aC\\
        C \rightarrow & AX_a\\
        B \rightarrow & c \mid X_cB\\
        X_a \rightarrow & a\\
        X_b \rightarrow & b\\
        X_c \rightarrow & c\\
\end{aligned}\]

Prüfen Sie mittels CYK-Algorithmus, ob das Wort \(aabacc\) in \(L(G)\) enthalten ist.
