#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: scrartcl
#+LATEX_CLASS_OPTIONS: [a4paper,14pt,ngerman]
#+OPTIONS: ':t toc:nil title:nil

#+LANGUAGE: de

#+LATEX_HEADER: \usepackage{polyglossia}
#+LATEX_HEADER: \setdefaultlanguage{german}
#+LATEX_HEADER: \PolyglossiaSetup{german}{shorthands=on}
#+LATEX_HEADER: \AtBeginDocument{\let\babelprovide\relax}
#+LATEX_HEADER: \AtBeginDocument{\let\shorthandon\relax}
#+LATEX_HEADER: \AtBeginDocument{\let\shorthandoff\relax}
#+LATEX_HEADER: \setmainfont{Gentium Book Basic}
#+LATEX_HEADER: \setsansfont{Latin Modern Sans}
#+LATEX_HEADER: \setmonofont{Latin Modern Mono}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{amsmath,amssymb}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{xurl}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \setstretch{1.3}

#+title: Übungsblatt 5

* *Übung 5*
** *Turingmaschinen*

*Hinweis*

Ist kein spezifischer Typ einer Turingmaschine in einer Aufgabe
gefordert, so ist eine 1-Band-Turingmaschine zu bevorzugen.

*** *Aufgabe 1*

Konstruieren Sie eine Turingmaschine, die das Wortproblem für die
Sprache \[L=\{a^nb^nc^nd^n \mid n\geq 0 \}\] entscheidet.

*** *Aufgabe 2*

Konstruieren Sie eine Turingmaschine, die das Wortproblem für die
Sprache \[L=\{w\tilde{w} \mid w \in \{a,b\}^*\}\] entscheidet.

*** *Aufgabe 3*

Konstruieren Sie eine 2-Band-Turingmaschine, die das Wortproblem für die
Sprache \[L=\{ww \mid w \in \{a,b\}^+\}\] entscheidet.

Gehen Sie davon aus, dass das Wort zu Beginn auf dem ersten Band stehe,
das zweite Band sei leer.

*** *Aufgabe 4*

Konstruieren Sie eine Turingmaschine, die das Wortproblem für die
Sprache \[L=\{w \in \{a,b,c\}^*\mid |w|_a=|w|_b=|w|_c\}\] entscheidet.
Hierbei ist \(|w|_a\) die Anzahl \(a\)'s im Wort \(w\).
